app:
  name: BudgetManagementApp

security:
  jwt:
    issuer: ${JWT_ISSUER:MyApp}
    secret: ${JWT_SECRET:defaultSecretKey}
    expiration: 600000 # 10 min
  refresh-token:
    expiration: 604800000 # 7 days
  verification-code:
    expiration: 1800000 # 30 min
    retry: 1800000 # 30 min
  secret-header-value: ${SECRET_HEADER:defaultSecretHeaderValue}

config:
  session:
    max-sessions: 5

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy_key}
  mail:
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE