app:
  name: BudgetManagementApp

security:
  issuer: ${JWT_ISSUER:MyApp}
  jwt:
    secret: ${JWT_SECRET:defaultSecretKey}
    expiration: 600000 # 10 min
  refresh-token:
    expiration: 604800000 # 7 days
  verification-code:
    expiration: 1800000 # 30 min
    retry: 1800000 # 30 min
  user-details-expiration: 600000 # 10 min
  reset-password-token:
    expiration: 1800000 # 30 min
    retry: 1800000 # 30 min

config:
  session:
    max-sessions: 5

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy_key}
  mail:
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 5MB #MAX FILE SIZE

aws:
  access-key: ${AWS_ACCESS_KEY:access-key}
  secret-key: ${AWS_SECRET_KEY:secret-key}
  region: eu-north-1
  s3:
    bucket-name: ${S3_BUCKET_NAME:bucket}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE