app:
  name: BudgetManagementApp

security:
  issuer: ${JWT_ISSUER:MyApp}
  jwt:
    secret: ${JWT_SECRET:defaultSecretKey}
    expiration: 600000 # 10 min
  refresh-token:
    expiration: 604800000 # 7 days
  verification-code:
    expiration: 1800000 # 30 min
    retry: 1800000 # 30 min
  reset-password-token:
    expiration: 1800000 # 30 min
    retry: 60000 # 1 min

config:
  session:
    max-sessions: 5
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:
          enum_type: STRING
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    mapper:
      accept-case-insensitive-enums: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: ${SPRING_AI_SCHEMA_INITIALIZATION:always}
  mail:
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 5MB #MAX FILE SIZE

aws:
  access-key: ${AWS_ACCESS_KEY:access-key}
  secret-key: ${AWS_SECRET_KEY:secret-key}
  region: eu-north-1
  s3:
    bucket-name: ${S3_BUCKET_NAME:bucket}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
